version: '3'
services:

  backend:
    container_name: SoundGroup-Backend
    image: sg-backend
    build: ./Backend/
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - FLASK_APP=Backend/api/__init__.py
#      - WAIT_HOSTS=mongo:27017
#      - MONGO_HOST=mongo
    volumes:
      - .:/code

  app:
    container_name: SoundGroup-Frontend
    image: sg-frontend
    command: nodemon index.js
    build: ./Frontend/
    ports:
      - "3000:3000"
    tty: true

  mongo:
    container_name: SoundGroup-MongoDB
    image: mongo
    volumes:
      - mongodata:/usr/share/mongodb/data
    ports:
      - "27017:27017"

volumes:
  mongodata:
