version: '3.2'

services:

  backend:
    container_name: SoundGroup-Backend
    image: backend
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      # code change detection - no need to rebuild image for container
      - .:/code
    
